name: CI via workflow_call

on:
  workflow_dispatch:

jobs:

  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump Runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"

  build_and_test:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/ci_integration_go.yml
    secrets: inherit

